# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='_author_test_+', to='store_db.Author'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='_publisher_test_+', to='store_db.Publisher'),
        ),
    ]
