# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_db', '0002_auto_20160309_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='test',
        ),
        migrations.AddField(
            model_name='publisher',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_publisher_test_models', to='store_db.Publisher'),
        ),
    ]
