# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_db', '0003_auto_20160310_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='free_international_shipping',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='international_shipping_company',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='international_shipping_cost',
        ),
    ]
