# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_db', '0004_auto_20160315_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='available_countries',
        ),
    ]
