# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_db', '0007_auto_20160317_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerrating',
            name='points',
            field=models.PositiveIntegerField(),
        ),
    ]
