# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_db', '0008_auto_20160317_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerrating',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_rank', to=settings.AUTH_USER_MODEL),
        ),
    ]
