# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_db', '0009_auto_20160317_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
