# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 03:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=52)),
                ('city_name', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
                ('street_address_line_1', models.CharField(max_length=60)),
                ('street_address_line_2', models.CharField(blank=True, max_length=60, null=True)),
                ('zipcode', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=15)),
                ('country_code_phone_number', models.CharField(max_length=5)),
                ('added_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=120)),
                ('sent_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPasswordVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=120)),
                ('sent_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture_url', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated_profile_picture_datetime', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('country_code_phone_number', models.CharField(blank=True, max_length=5, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verified_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_phone_number_verified', models.BooleanField(default=False)),
                ('phone_number_verified_datetime', models.DateTimeField(blank=True, null=True)),
                ('phone_number_updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_updated_password_datetime', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserExtended'),
        ),
    ]
