# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160315_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='country_code_phone_number',
            field=models.CharField(blank=True, default='+1', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
